Init project
pisarevaa/gophermart pull request #1
Opened 2024-06-12 09:04 UTC by pisarevaa

2024-06-13 16:00 UTC, pisarevaa commented
Дмитрий, сделал проект на основе фреймворка Gin, добавил Swagger документацию по ручкам, написал unit-тесты и единый интеграционный тест для проверки работы всей цепочки Какие остались вопросы?
1. Один из тестов не проходит (писал в чате), пока не понимаю почему
2. По фоновой задаче пока сделал простую реализацию, на 1:1 интересно обсудить какие варианты ещеможно сделать
3. На 1:1 покажу unit тест который не понимаю как замокать правильно (TestWithdrawBalance)

2024-06-16 18:55 UTC, gonozov0 requested changes
Все отлично реализовал, отписал только мелкие моменты 👍
Если есть возможности и желание пройти более хардовое ревью (если бы это было реальное ревью нового сервиса на моем проекте), то тут 2 момента:
1. стоит реализовать отдельный inmemory storage для юнит тестов
2. стоит разбить приложение на слои (не важно по какому подходу, clean, ddd, hexagonal, но я больше шарю за ddd). Сейчас как минимум отсутствует слой бизнес логики

2024-06-16 18:55 UTC, gonozov0 commented on cmd/accrual/main.go
А это уже было в шаблоне проекта, или ты сам написал?
Раньше вроде только бинарники давали внешнего сервиса

2024-06-16 18:55 UTC, gonozov0 commented on integration_test.go
> +	suite.Require().True(successRegister.Success)
Лучше вместо комментов выделять прям в отдельный подтест
```go
s.Run("Регистрация пользователя", func() {
     ...
```

2024-06-16 18:55 UTC, gonozov0 commented on internal/server/handlers/balance_test.go
> +// Пока не понимаю как замокать DBTransaction, вернусь позже
Напиши полноценный inmemory storage под тесты и подставляй его

2024-06-16 18:55 UTC, gonozov0 commented on Makefile
> +	go test -v ./e2e_test/...
эти 2 команды у тебя явно не работают + стоит также добавить команду для генерации swagger или включить его в go generate

2024-06-17 18:07 UTC, pisarevaa commented on cmd/accrual/main.go
Удалил сервис accrual

2024-06-18 18:30 UTC, pisarevaa commented
@gonozov0 привет, капитально улучшил проект, добавил in-memory движок, получилось полечить внешние тесты проекта, сделал собственные unit-тесты в двух вариациях c моком БД и in-memory движок, полечил проблему с одним тестом, по твоим комментариям отработал. Пока тяжко идет деление приложения на слои, сижу изучаю подходы, выделю на это больше времени чтобы продвинуться по этой теме

2024-06-19 12:36 UTC, gonozov0 approved these changes
Супер, отлично доработал историю с inmemory для тестов + здорово, что полечился тест
Историю со слоями тогда дожидаться не будем, апрувну сейчас, если успеешь до моего отпуска, то напиши в личку или запишись на 1:1, посмотрим дополнительно)

2024-06-27 11:02 UTC, merged